### ISSUE TITLE
meet this error when launch ue uproject file  with ue5.4.2-v67 version

### ISSUE THREAD

**Issue by lihaiecnu** [oculus-samples/Unreal-MetaXRAudioSDK#1]
LoginId:32a315d9473c2def9c08acbf095cf2b5
EpicAccountId:695c487aa45943f2b70def42cc811646

Assertion failed: DllHandle [File:E:\lihai_MRDev\UE5\Engine\Source\Runtime\Core\Private\Windows\WindowsPlatformProcess.cpp] [Line: 196] 

UnrealEditor_Core!FWindowsPlatformProcess::GetDllExport() [E:\lihai_MRDev\UE5\Engine\Source\Runtime\Core\Private\Windows\WindowsPlatformProcess.cpp:196]
UnrealEditor_MetaXRAudio!FMetaXRAudioLibraryManager::GetPluginContext() [E:\lihai_MRDev\UE5\Engine\Plugins\Runtime\OculusXR\MetaXRAudio\Source\MetaXRAudio\Private\MetaXRAudioDllManager.cpp:250]
UnrealEditor_MetaXRAudio!FMetaXRAudioLibraryManager::UpdatePluginContext() [E:\lihai_MRDev\UE5\Engine\Plugins\Runtime\OculusXR\MetaXRAudio\Source\MetaXRAudio\Private\MetaXRAudioDllManager.cpp:240]
UnrealEditor_MetaXRAudio!UMetaXRAudioAcousticSettings::UMetaXRAudioAcousticSettings() [E:\lihai_MRDev\UE5\Engine\Plugins\Runtime\OculusXR\MetaXRAudio\Source\MetaXRAudio\Private\MetaXRAudioAcousticSettings.cpp:26]
UnrealEditor_CoreUObject!UClass::CreateDefaultObject() [E:\lihai_MRDev\UE5\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:4586]
UnrealEditor_CoreUObject!UClass::InternalCreateDefaultObjectWrapper() [E:\lihai_MRDev\UE5\Engine\Source\Runtime\CoreUObject\Private\UObject\Class.cpp:5190]
UnrealEditor_CoreUObject!UObjectLoadAllCompiledInDefaultProperties() [E:\lihai_MRDev\UE5\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectBase.cpp:809]
UnrealEditor_CoreUObject!ProcessNewlyLoadedUObjects() [E:\lihai_MRDev\UE5\Engine\Source\Runtime\CoreUObject\Private\UObject\UObjectBase.cpp:894]
UnrealEditor!FEngineLoop::PreInitPostStartupScreen() [E:\lihai_MRDev\UE5\Engine\Source\Runtime\Launch\Private\LaunchEngineLoop.cpp:3803]
UnrealEditor!GuardedMain() [E:\lihai_MRDev\UE5\Engine\Source\Runtime\Launch\Private\Launch.cpp:136]
UnrealEditor!GuardedMainWrapper() [E:\lihai_MRDev\UE5\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:118]
UnrealEditor!LaunchWindowsStartup() [E:\lihai_MRDev\UE5\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:258]
UnrealEditor!WinMain() [E:\lihai_MRDev\UE5\Engine\Source\Runtime\Launch\Private\Windows\LaunchWindows.cpp:298]
UnrealEditor!__scrt_common_main_seh() [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288]
kernel32
ntdll

than i how to fix this problem

**Comment by lance-at-meta** [comment]
Hey @lihaiecnu! Thanks for the question and feedback.

That error is indeed curious to me. I just tested on a new machine with a brand new setup (fresh installs of everything) and was using UE5.4.4 and v67 of the MetaXRAudio plugin as well as v67 of the MetaXR plugin. Everything loaded up and and built correctly using that new setup. I was able to load the built .apk on my quest 3 device and run it without issue. I was also able to use Quest link when entering play in editor mode in Unreal using my headset.

The stack you've copy/pasted doesn't seem to line up to the v67 source code though as far as I can tell. Line 240 of MetaXRAudioDllManager.cpp in v67 calls `UMetaXRAudioRoomAcousticProperties::GetActiveRoomAcoustics();` but the stack says it's calling `FMetaXRAudioLibraryManager::UpdatePluginContext()`. This makes me not trust the frames of the stack are correct and to me suggest a symbolication error but I might be simply misunderstanding.

If I we can/should trust that stack: the next frame, with the call to the plug-ins pre-built binary in line 250 of `MetaXRAudioDllManager.cpp` (i.e. the `OVRA_CALL(ovrAudio_GetPluginContext)`), fails with an error about an invalid DLL handle as far as I can tell. But this handle should be have assigned/set when the plug-in was loaded in line 13 of IMetaXRAudioPlugin.cpp. 

Can you double check that there is indeed a DLL sitting in the MetaXRAudio/Binaries/Win64 directory of the installed plug-in? If you've repackaged the plug-in to a different engine version (which I can't imagine you would have as v67 should be targeted to UEv5.4 already), that binary might need to be manually copied over. For more information, see the ["Repackaging for a different version of Unreal Engine" in the Oculus Developer Center](https://developer.oculus.com/documentation/unreal/meta-xr-audio-sdk-unreal-req-setup/) for more information.

Maybe one thing to mention is that when I set up the new build machine I tested with, I noted that certain versions of the MS SDK were not allowed by Unreal due to "compiler issues". I had to download older versions that were compatible with the engine's project. Perhaps you  might be using a version of the MSDK not permitted? Just a guess but if so, generate VS solutions for the project by right clicking on the .uproject file and observing if there are any errors in Visual Studio that might need resolution.

Another thing you might want to try is using v66 of the MetaXRAudio and MetaXR plug-ins to test. These don't have any acoustics scripts and thus would remove the offending code. You can also try upgrading the project to the latest 5.4 version, which as of this writing is 5.4.4 as far as I can tell.

Let us know how it goes or if you're able to resolve this. You might be hitting a problem others are having and if we can get to the bottom of it, we'll happily update the project, plugin, or documentation code accordingly.
